export const CARD_VARIANT_EMBASSADOR = 'CARD_VARIANT_EMBASSADOR';
export const CARD_VARIANT_ASSASSIN = 'CARD_VARIANT_ASSASSIN';

export type CardVariant = typeof CARD_VARIANT_ASSASSIN | typeof CARD_VARIANT_EMBASSADOR;
